@startuml dist_2sms_one

Tag ->(20) Anchor : Pull_One
note left 
    Сохр req_tx_ts
end note
note right
    Сохр req_rx_ts
end note

Anchor ->(20) Tag : Response_One (req_rx_ts, ans_tx_ts)
note left
    Сохр ans_rx_ts
end note
note right
    Сохр ans_tx_ts
end note
note over Tag
    (req_rx_ts - ans_rx_ts) - (req_rx_ts - ans_tx_ts)
end note
@enduml