@startuml dist_2sms_one

title Простой протокол на двух смс, возможны сильные погрешности

Tag ->(20) Anchor : Pull_SS
note left 
    Сохр pull_tx_ts
end note
note right
    Сохр pull_rx_ts
end note

Anchor ->(20) Tag : Response_SS\n(pull_rx_ts, resp_tx_ts)
note left
    Сохр resp_rx_ts
end note
note right
    Сохр resp_tx_ts
end note
note over Tag
    (pull_tx_ts - resp_rx_ts) - (resp_tx_ts - pull_rx_ts)
end note
@enduml
