@startuml state

[*] --> Reset
Reset : Общение сборещено, надо начать сначала

Reset --> Pulled : Pull
Pulled : Отправка Response

Pulled --> Finaled : Final
Pulled --> Reset
Finaled : отправка Distance

Finaled --> Reset

@enduml